// Generated by CoffeeScript 1.6.3
(function() {
  var actions, states;
  actions = ['call', 'conference', 'intercom', 'transfer', 'toggle', 'ghostListen', 'ghostHelp', 'ghostConference', 'endCall'];
  return states = {
    state: ['disconnected', 'ready', 'ring', 'backring', 'call', 'talk'],
    webrtc: [true, false],
    callcenter: [true, false],
    conference: [true, false],
    status: ['ready', 'dnd', 'redirect', 'ccready', 'ccbreak']
  };
})();
